### ISSUE TITLE
C++ concepts file compiles on Godbolt but not on clang++ on macOS

### ISSUE THREAD

**Issue by hameerabbasi** [conda-forge/clangdev-feedstock#129]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
# packages in environment at /Users/hameerabbasi/mambaforge/envs/xtensor:
#
# Name                    Version                   Build  Channel
bzip2                     1.0.8                hc929b4f_4    conda-forge
c-ares                    1.17.1               hc929b4f_0    conda-forge
c-compiler                1.1.3                h35c211d_0    conda-forge
ca-certificates           2020.12.5            h033912b_0    conda-forge
cctools                   949.0.1             hd9211c8_19    conda-forge
cctools_osx-64            949.0.1             h2f0f38f_19    conda-forge
clang                     11.0.1               h694c41f_1    conda-forge
clang-11                  11.0.1          default_hf8bb9ca_1    conda-forge
clang-tools               11.0.1          default_hf8bb9ca_1    conda-forge
clang_osx-64              11.0.1               hb91bd55_0    conda-forge
clangxx                   11.0.1          default_hf8bb9ca_1    conda-forge
clangxx_osx-64            11.0.1               h7e1b574_0    conda-forge
cmake                     3.19.3               hb0787d7_0    conda-forge
compiler-rt               11.0.1               h654b07c_0    conda-forge
compiler-rt_osx-64        11.0.1               h8c5fa43_0    conda-forge
compilers                 1.1.3                h694c41f_0    conda-forge
cxx-compiler              1.1.3                h926bf3e_0    conda-forge
expat                     2.2.9                h046ec9c_3    conda-forge
fortran-compiler          1.1.3                h6818c3e_0    conda-forge
gfortran_impl_osx-64      9.3.0               h8668ab3_17    conda-forge
gfortran_osx-64           9.3.0               h0d18d9c_12    conda-forge
gmp                       6.2.1                h2e338ed_0    conda-forge
gtest                     1.10.0               h926bf3e_7    conda-forge
isl                       0.22.1               hb1e8313_2    conda-forge
krb5                      1.17.2               h60d9502_0    conda-forge
ld64                      530                 hd2e7500_19    conda-forge
ld64_osx-64               530                 hea264c1_19    conda-forge
ldid                      2.1.2                h7660a38_2    conda-forge
libclang-cpp11            11.0.1          default_hf8bb9ca_1    conda-forge
libcurl                   7.71.1               h9bf37e3_8    conda-forge
libcxx                    11.0.1               habf9029_0    conda-forge
libedit                   3.1.20191231         hed1e85f_2    conda-forge
libev                     4.33                 haf1e3a3_1    conda-forge
libgfortran               5.0.0           9_3_0_h6c81a4c_17    conda-forge
libgfortran-devel_osx-64  9.3.0               h6c81a4c_17    conda-forge
libgfortran5              9.3.0               h6c81a4c_17    conda-forge
libiconv                  1.16                 haf1e3a3_0    conda-forge
libllvm11                 11.0.1               h223d4b2_0    conda-forge
libnghttp2                1.41.0               h7580e61_2    conda-forge
libssh2                   1.9.0                h39bdce6_5    conda-forge
libuv                     1.40.0               haf1e3a3_0    conda-forge
llvm-openmp               8.0.1                h770b8ee_0    conda-forge
llvm-tools                11.0.1               h223d4b2_0    conda-forge
make                      4.3                  h22f3db7_1    conda-forge
mpc                       1.1.0             ha57cd0f_1009    conda-forge
mpfr                      4.0.2                h72d8aaf_1    conda-forge
ncurses                   6.2                  h2e338ed_4    conda-forge
openmp                    8.0.1                         0    conda-forge
openssl                   1.1.1i               h35c211d_0    conda-forge
rhash                     1.4.1                h35c211d_0    conda-forge
tapi                      1100.0.11            h879752b_0    conda-forge
tk                        8.6.10               hb0a8c7a_1    conda-forge
xsimd                     7.4.9                h926bf3e_2    conda-forge
xtl                       0.7.1                h926bf3e_0    conda-forge
xz                        5.2.5                haf1e3a3_1    conda-forge
zlib                      1.2.11            h7795811_1010    conda-forge
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

     active environment : xtensor
    active env location : /Users/hameerabbasi/mambaforge/envs/xtensor
            shell level : 1
       user config file : /Users/hameerabbasi/.condarc
 populated config files : /Users/hameerabbasi/mambaforge/.condarc
                          /Users/hameerabbasi/.condarc
          conda version : 4.9.2
    conda-build version : not installed
         python version : 3.8.6.final.0
       virtual packages : __osx=10.16=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /Users/hameerabbasi/mambaforge  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /Users/hameerabbasi/mambaforge/pkgs
                          /Users/hameerabbasi/.conda/pkgs
       envs directories : /Users/hameerabbasi/mambaforge/envs
                          /Users/hameerabbasi/.conda/envs
               platform : osx-64
             user-agent : conda/4.9.2 requests/2.22.0 CPython/3.8.6 Darwin/20.3.0 OSX/10.16
                UID:GID : 501:20
             netrc file : None
           offline mode : False

```
</details>

Here's the file on [GodBolt](https://godbolt.org/z/3KWGTb):

```c++
#include <utility>
#include <concepts>

template <typename T, typename... I, typename IK, typename P>
    concept coordinate_value_iterable =
        std::same_as<typename T::position_t, P> &&
        std::same_as<typename T::value_t, IK> &&
        std::integral<typename T::position_t> &&
        std::integral<typename T::value_t> &&
        (std::integral<I> &&...) &&
        requires(T t, I... i, IK ik, P p) {
            { t.coord_bounds(i..., p) } -> std::same_as<std::pair<typename T::value_t, typename T::value_t> >;
            { t.coord_access(p, i..., ik) } -> std::same_as<typename T::position_t>;
        };
```

```bash
$ clang++ a.cpp -std=c++20 -Wall -pedantic
a.cpp:8:14: error: no member named 'integral' in namespace 'std'
        std::integral<typename T::position_t> &&
        ~~~~~^
a.cpp:8:45: error: expected '(' for function-style cast or type construction
        std::integral<typename T::position_t> &&
                      ~~~~~~~~~~~~~~~~~~~~~~^
a.cpp:9:9: error: use of address-of-label extension outside of a function body
        std::integral<typename T::value_t> &&
        ^
3 errors generated.
```

**Comment by isuruf** [comment]
This is not a support forum for clang and libc++. Please ask upstream about C++ concepts status.

**Comment by hameerabbasi** [comment]
C++20 concepts works in Clang 11.0.1. If you look at the Godbolt, it shows that this code snippet works, whereas it doesn't in a conda-installed version, which is why I believe it's a packaging issue.

**Comment by jakirkham** [comment]
Are you sure there are not some special flags that need to be added to get this to compile?

**Comment by hameerabbasi** [comment]
I used the flags from the Godbolt.

**Comment by hameerabbasi** [comment]
Here's a smaller, less fancy repro-er:

```
#include <concepts>

template <typename T>
    concept is_int = std::integral<T>;
```

**Comment by isuruf** [comment]
As I said earlier this is not a conda-forge issue. If you took the time to look at the `concepts` file, you'll see that `integral` is not supported in libc++. Please do some research before commenting.
